const DEMO_MODE = process.env.DEMO_MODE === 'true';

/**
 * Génère un email pour un lead détecté
 * @param {Object} lead - lead enrichi via FullEnrich ou simulation
 */
function generateGTMEmail(lead) {
    const subjectPrefix = DEMO_MODE ? "[DEMO]" : "[PRODUCTION]";

    return {
        subject: `${subjectPrefix} Opportunity with ${lead.company} - ${lead.article_title.substring(0, 50)}...`,
        body: `Hi ${lead.name || "there"},

I noticed ${lead.company} was mentioned in the news:
"${lead.article_title || "N/A"}"

As ${lead.title || "your role"}, I believe our GTM automation platform could help you capitalize on this growth momentum.

Would you be available for a 15-minute call next week?

Best regards,
The GTM-Agent Team

---
This email was automatically generated by GTM-Agent
Mode: ${DEMO_MODE ? "Demo" : "Production"}
Detection: ${lead.detected_at || "N/A"}
Enrichment: ${lead.enriched_at || "N/A"}
Status: ${lead.status || "N/A"}
Source: ${lead.source || "N/A"}`,
        to: lead.email || "unknown@example.com",
        from: "gtm-agent@hackathon.com",
        timestamp: new Date().toISOString()
    };
}

module.exports = { generateGTMEmail };