// src/utils/emailGenerator.js

/**
 * Generate GTM email for a given lead
 */
function generateGTMEmail(lead) {
    return {
        subject: `Opportunity with ${lead.company} - ${lead.article_title.substring(0, 50)}...`,
        body: `Hi ${lead.name},

I noticed ${lead.company} was mentioned in the news:
"${lead.article_title}"

As ${lead.title}, I believe our GTM automation platform could help you capitalize on this growth momentum.

Would you be available for a 15-minute call next week?

Best regards,
The GTM-Agent Team

---
This email was automatically generated by GTM-Agent
Detection: ${lead.detected_at}
Enrichment: ${lead.enriched_at}
Status: ${lead.status}`,
        to: lead.email,
        from: "gtm-agent@hackathon.com",
        timestamp: new Date().toISOString()
    };
}

module.exports = { generateGTMEmail };