function generateGTMEmail(lead) {
    // Fallback values
    const company = lead.company || 'Unknown Company';
    const articleTitle = lead.article_title || 'No title available';
    const name = lead.name || 'Valued Contact';
    const title = lead.title || 'Decision Maker';
    const email = lead.email || 'contact@example.com';
    const detectedAt = lead.detected_at || new Date().toISOString();
    const status = lead.status || 'Qualified';
    
    // Déterminer le mode dynamiquement
    // Si l'email est demo@example.com ou le nom est Demo User, c'est le mode demo
    const isDemo = email === 'demo@example.com' || lead.name === 'Demo User';
    const mode = isDemo ? 'DEMO' : 'PRODUCTION';

    return {
        subject: `[${mode}] Opportunity with ${company} - ${articleTitle.substring(0, 50)}${articleTitle.length > 50 ? '...' : ''}`,
        body: `Hi ${name},

I noticed ${company} was mentioned in the news:
"${articleTitle}"

As ${title}, I believe our GTM automation platform could help you capitalize on this growth momentum.

Would you be available for a 15-minute call next week?

Best regards,
The GTM-Agent Team

---
This email was automatically generated by GTM-Agent
Detection: ${detectedAt}
Status: ${status}
Mode: ${mode}`,
        to: email,
        from: "gtm-agent@hackathon.com",
        timestamp: new Date().toISOString()
    };
}

module.exports = { generateGTMEmail };